name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle

        run: chmod +x gradlew && ./gradlew build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t runner-app:latest .
          docker tag runner-app:latest ${{ secrets.DOCKER_USERNAME }}/runner-app:latest

      - name: Push the Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/runner-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Latest Image
        run: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/runner-app:latest

      - name: Stop Current Running Container
        run: |
          sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

      - name: Run Latest Image
        run: |
          sudo docker run --name api-server -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/runner-app:latest

      - name: Delete Old Image
        run: |
          sudo docker system prune -f
