name: cd pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Change permission
        run: |
          sudo chown -R ${{ secrets.NAME }}:${{ secrets.PASSWORD }} /home/actions-runner/_work/runner-test

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: /home/actions-runner/_work/runner-test

      - name: Deploy
        run: |
          sudo java -jar /home/actions-runner/_work/runner-test/build/libs/runnertest-0.0.1-SNAPSHOT.jar
